trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'myResourceGroup'
  templateFile: 'storageAccount.json'
  parametersFile: 'storageAccount.parameters.json'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '<Your-Service-Connection-Name>'
    subscriptionId: '<Your-Subscription-ID>'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    csmParametersFile: '$(parametersFile)'
    deploymentMode: 'Incremental'
