trigger:
- main

variables:
  location: 'East US'
  storageAccountName: 'mystorageacctdemo123'

stages:
- stage: Deploy
  jobs:
  - job: DeployStorage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'serviceconnection1'
        subscriptionId: 'b56841e0-d756-4c89-b7dd-9ac1739b47e2'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'newdemo'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: 'storageaccount.json'
        overrideParameters:   '-storageAccountName mystorageacctdemo123'

